pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com


test:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com

production:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com
