pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30

development:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com
  username: sviat
  password: colloboration28

test:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com
  username: sviat
  password: colloboration28

production:
  <<: *pg
  database: kittensStore
  host: kittensstore.cywnmrcl4f2s.us-east-1.rds.amazonaws.com
  username: sviat
  password: colloboration28
